<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Osahmodule\Module'                        => __DIR__ . '/Module.php',
    'Osahmodule\Controller\SkeletonController' => __DIR__ . '/src/Osahmodule/Controller/SkeletonController.php',
    'OsahmoduleTest\Framework\TestCase'        => __DIR__ . '/tests/Osahmodule/Framework/TestCase.php',
    'OsahmoduleTest\SampleTest'                => __DIR__ . '/tests/Osahmodule/SampleTest.php',
);
