<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Osahform\Module'                        => __DIR__ . '/Module.php',
    'Osahform\Controller\OsahformController' => __DIR__ . '/src/Osahform/Controller/OsahformController.php',
    'OsahformTest\Framework\TestCase'        => __DIR__ . '/tests/Osahform/Framework/TestCase.php',
    'OsahformTest\SampleTest'                => __DIR__ . '/tests/Osahform/SampleTest.php',
);
