            <div class="dds-title-block">
                <div class="container">
                    <div class="dds-title-wrapper">
                        <div class="col-xs-12">
                            <h2>DDS Import & Reports</h2>
                        </div>
                    </div>
                </div>
            </div>
            <div class="tab-block">
                <div class="container">
                    <ul>
                        <li>
                            <a ui-sref="ddsimport"><i class="fa fa-download" aria-hidden="true"></i> Import</a>
                        </li>
                        <li>
                            <a ui-sref="ddsreport"  class="active"><i class="fa fa-book" aria-hidden="true"></i> Reports</a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="dds-reports-block">
                <div class="container">
                    <div class="dds-reports-wrapper">
                        <div class="report-select-date-block">
                            <div class="col-xs-2">
                                <label>Select Date</label>
                                <div class="datepicker-wrapper">
                                    <input  type="text" id="datepicker1">
                                    <i class="fa fa-calendar" aria-hidden="true"></i>
                                </div>
                            </div>
                            <a class="search-btn"><i class="fa fa-search" aria-hidden="true"></i> Search</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="dds-report-table-block">
                <div class="container">
                    <div class="col-xs-12">
                        <div class="display-records-label">
                            <h2>Displaying 1-10 records of 100</h2>
                        </div>
                    </div>
                    <div class="col-xs-12">
                        <div class="page-number-btn-block">
                            <div class="col-xs-6">
                                <div class="dropdown">
                                    <label>Entries per page</label>
                                    <select>
                                        <option>1</option>
                                        <option>2</option>
                                        <option>3</option>
                                    </select>
                                </div>
                            </div>
                            <div class="col-xs-6">
                                <div class="btn-block">
                                    <a><i class="fa fa-print" aria-hidden="true"></i> PRINT ALL</a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-xs-12">
                        <div class="dds-report-table">
                            <table>
                                <tr class="heading">
                                    <td class="docket">Docket <i class="fa fa-angle-down" aria-hidden="true"></i></td>
                                    <td class="case-name">Record ID <i class="fa fa-angle-down" aria-hidden="true"></i></td>
                                </tr>
                                <tr>
                                    <td>1600079</td>
                                    <td>214435</td>
                                </tr>
                                <tr>
                                    <td>1600079</td>
                                    <td>214435</td>
                                </tr>
                                <tr>
                                    <td>1600079</td>
                                    <td>214435</td>
                                </tr>
                                <tr>
                                    <td>1600079</td>
                                    <td>214435</td>
                                </tr>
                                <tr>
                                    <td>1600079</td>
                                    <td>214435</td>
                                </tr>
                                <tr>
                                    <td>1600079</td>
                                    <td>214435</td>
                                </tr>
                            </table>
                        </div>
                    </div>
                    <div class="col-xs-12">
                        <div class="table-pagination">
                            <nav aria-label="Page navigation">
                                <ul class="pagination">
                                    <li>
                                        <a href="#" aria-label="First">
                                            <i class="fa fa-angle-double-left" aria-hidden="true"></i> First
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#" aria-label="Previous">
                                            <i class="fa fa-angle-left" aria-hidden="true"></i> Prev
                                        </a>
                                    </li>
                                    <li><a class="active" href="#">1</a></li>
                                    <li><a href="#">2</a></li>
                                    <li><a href="#">3</a></li>
                                    <li><a href="#">4</a></li>
                                    <li><a href="#">5</a></li>
                                    <li>
                                        <a href="#" aria-label="Next">
                                            Next <i class="fa fa-angle-right" aria-hidden="true"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#" aria-label="Last">
                                            Last <i class="fa fa-angle-double-right" aria-hidden="true"></i>
                                        </a>
                                    </li>
                                </ul>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>
      