
            <div class="new-docket-title-block">
                <div class="container">
                    <div class="new-docket-title-wrapper">
                        <div class="col-xs-8">
                            <h2>Docket New Case</h2>
                        </div>
                        <div class="col-xs-4">
                            <span class="createdby-label">Created By: </span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="tab-block">
                <div class="container">
                    <ul>
                        <li>
                            <a ui-sref="newdocket" class="active"><i class="fa fa-info-circle" aria-hidden="true"></i> General Information</a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="docket-information-block">
                <div class="docket-information-left col-xs-5">
                    <div class="docket-info-block">
                        <h2>OSAH Form 1 Information</h2>
                        <div class="col-xs-6">
                            <label>Agency Code *</label>
                           <!--  <span ng-bind="agencyCode"></span> -->   
                            <div class="dropdown">
                                <select  ng-model="agencyCode" id="new_docket-agencyCode"  name="agencyCode">
									<option value="DDS" selected>DDS</option>
                                </select>
                            </div>
                        </div>
                        <div class="col-xs-6">
                            <label>Case Type *</label>
							<div class="dropdown">
                                <select  ng-model="casetypeselect" id="new_docket-casetypeselect" name="casetypeselect" >
									<option value="ALS" selected>ALS</option>
                                </select>
                            </div>
                        </div>
                        <div class="col-xs-6">
                            <label>County</label>
                             <div class="dropdown">
                                <select  ng-change="casetypeCountyChange()" ng-model="countyselect" id="new_docket-countyselect">
                                    <option value="No County">No County</option>
                                    <option conty="{{countylist.CountyID}}" ng-repeat="countylist in countyList_root | orderBy :'Countydescription'" value="{{countylist.Countydescription}}">{{countylist.Countydescription}}</option>
                                </select>
                            </div>
                        </div>
                        <div class="col-xs-6">
                            <label>Date Requested *</label>
                            <div class="datepicker-wrapper">
                                <input type="text" id="new_docket-reqdate" class="add_doc" ng-model="dateRequested" msg="Please select requested date!">
                                <i class="fa fa-calendar" aria-hidden="true"></i>
                            </div>
                        </div>
                        <div class="col-xs-6">
                            <label>Agency Ref Number*</label>
                            <input type="text" id="new_docket-agencyrefnumber" ng-model="agencyrefnumber" msg="Please select agency reference number!" class="add_doc" name="agencyrefnumber"/>
                        </div>
                        <div class="col-xs-6">
                            <label>Hearing Type</label>
                            <div class="dropdown" >
                                <select  ng-model="hearingType" class="disable" name="hearingType" id="new_docket-hearingType" disabled="disabled">
                                    <option value="{{hearType.HearingValues}}"  ng-repeat="hearType in hearingTypedetails" >{{hearType.HearingValues}}</option>
                                </select>
                            </div>
                        </div>
						<h2>Temporary Permit</h2>
						<div class="col-xs-6">
                            <label>Eligible for a Permit?</label>
                            <div class="dropdown">
                                <select ng-model="elgpermit" name="elgpermit" id="new_docket-elegpermit" class="" >
                                    <option value="0">No</option>
									<option value="1">Yes</option>
                                </select>
                            </div>
                        </div>                     
						<div ng-hide="elgpermit == 0">
							<div class="col-xs-6">
									<label>Permit Effective Date <span class="astrisk" ng-if="elgpermit == 1">*</span></label>
									<div class="datepicker-wrapper">
										<input  type="text" ng-model="effectivedate" ng-class="{add_doc: elgpermit == 1}" ng-change ="getPermitExpiryDate()"  msg="Please Select Permit Effective Date." id="new_docket-effectivedate" min="{{effectivedate | date:'yyyy-MM-dd'}}">
										<i class="fa fa-calendar" aria-hidden="true"></i>
									</div>
								</div>
								<div class="col-xs-6">
									<label>Permit Expiration Date <span class="astrisk" ng-if="elgpermit == 1">*</span></label>
									<div class="datepicker-wrapper">
										<input  type="text" ng-model="expirydate" ng-class="{add_doc: elgpermit == 1}"  msg="Please Select Permit Expiration Date." id="expirydate" min="{{expirydate | date:'yyyy-MM-dd'}}">
										<i class="fa fa-calendar" aria-hidden="true"></i>
									</div>
								</div>
								<div class="col-xs-6">
									<label>Date of Birth <span class="astrisk" ng-if="elgpermit == 1">*</span></label>
									<div class="datepicker-wrapper">
										<input  type="text" ng-model="dob" ng-class="{add_doc: elgpermit == 1}"  msg="Please Select Date of Birth." id="dob" min="{{dob | date:'yyyy-MM-dd'}}">
										<i class="fa fa-calendar" aria-hidden="true"></i>
									</div>
								</div>
								<div class="col-xs-6">
									<label>Incident Date <span class="astrisk" ng-if="elgpermit == 1">*</span></label>
									<div class="datepicker-wrapper">
										<input  type="text" ng-model="incident_date" ng-class="{add_doc: elgpermit == 1}"  msg="Please Select Incident Date." id="incident_date" min="{{incident_date | date:'yyyy-MM-dd'}}">
										<i class="fa fa-calendar" aria-hidden="true"></i>
									</div>
								</div>
						</div>
                    </div>
                    
                    <div class="btn-block">
                        <button type="submit" ng-click="addDocket()"  class="btn btn-default search-btn" toggle-class="clickevent" ng-disabled="isDisabled">SAVE</button>
                    </div>
                </div>
                <div class="docket-information-right col-xs-7">
                    <div class="docket-info-right-block">
                        <h2>Document & File Management</h2>
                        <div class="button-block">
                            <a class="disable"><i class="fa fa-plus" aria-hidden="true"></i> DOCUMENT TEMPLATES</a>
                            <a class="disable"><i class="fa fa-plus" aria-hidden="true"></i> FILES</a>
                        </div>
                        <div style="display: none;">
                            <table>
                                <tr class="heading">
                                    <td>&nbsp;</td>
                                    <td>Document <i class="fa fa-chevron-down" aria-hidden="true"></i></td>
                                    <td>Name <i class="fa fa-chevron-down" aria-hidden="true"></i></td>
                                    <td>Date <i class="fa fa-chevron-down" aria-hidden="true"></i></td>
                                    <td>Description <i class="fa fa-chevron-down" aria-hidden="true"></i></td>
                                    <td>&nbsp;</td>
                                </tr>
                                <tr class="table-row">
                                    <td><i class="fa fa-pencil" aria-hidden="true"></i></td>
                                    <td>Notice of Hearing</td>
                                    <td class="name-data">Noticeofhearing_160 0045.docx</td>
                                    <td>09/02/2016</td>
                                    <td>Lorem ipsum dolor sit amet, consectetur adipisicing elit</td>
                                    <td><i class="fa fa-trash" aria-hidden="true"></i></td>
                                </tr>
                                <tr class="table-row">
                                    <td><i class="fa fa-pencil" aria-hidden="true"></i></td>
                                    <td>Decision</td>
                                    <td class="name-data">OSAHDocument.pdf</td>
                                    <td>09/02/2016</td>
                                    <td>Dismissal</td>
                                    <td><i class="fa fa-trash" aria-hidden="true"></i></td>
                                </tr>
                            </table>
                        </div>
                    </div>
                    <div class="disposition-block">
                        <h2>Disposition</h2>
                        <div style="display: none;">
                            <div class="col-xs-3">
                                <label>Disposition Type</label>
                                <span>Dismissed</span>
                            </div>
                            <div class="col-xs-3">
                                <label>Hearing? (Yes/No)</label>
                                <span>Yes</span>
                            </div>
                        </div>
                        <div style="display: none;">
                            <div class="col-xs-3">
                                <label>Disposition Date</label>
                                <span>05/15/2016</span>
                            </div>
                            <div class="col-xs-3">
                                <label>Date Signed by Judge</label>
                                <span>05/15/2016</span>
                            </div>
                            <div class="col-xs-3">
                                <label>Date Mailed</label>
                                <span>05/15/2016</span>
                            </div>
                        </div>
                        <div style="display: none;">
                            <a class="reopen-case-button">ReOpen Case</a>
                        </div>
                        <div>
                            <a class="add-decision-btn"><i class="fa fa-plus" aria-hidden="true"></i> ADD DECISION</a>
                        </div>
                    </div>
                    <div class="party-info-block">
                        <h2>Party Information</h2>
                        <div>
                            <a class="add-party-btn" ><i class="fa fa-plus" aria-hidden="true"></i> ADD PARTY</a>
                        </div>
                        <div style="display: none;">
                            <div class="col-xs-6">
                                <div class="party-block">
                                    <div class="heading">
                                        <span>Petitioner</span>
                                        <span>
                                            <i class="fa fa-pencil" aria-hidden="true"></i>
                                            <i class="fa fa-trash" aria-hidden="true"></i>
                                        </span>
                                    </div>
                                    <div class="party-body">
                                        <p>Williams, Teresa</p>
                                        <p>
                                            <label><i class="fa fa-phone" aria-hidden="true"></i> Phone:</label>
                                            <span>(404) 645-8888</span>
                                        </p>
                                        <p>
                                            <label><i class="fa fa-envelope-o" aria-hidden="true"></i> Email:</label>
                                            <span></span>
                                        </p>
                                        <p>
                                            <label><i class="fa fa-fax" aria-hidden="true"></i> Fax:</label>
                                            <span></span>
                                        </p>
                                    </div>
                                </div>
                            </div>
                            <div class="col-xs-6">
                                <div class="party-block">
                                    <div class="heading">
                                        <span>Respondant</span>
                                        <span>
                                            <i class="fa fa-pencil" aria-hidden="true"></i>
                                            <i class="fa fa-trash" aria-hidden="true"></i>
                                        </span>
                                    </div>
                                    <div class="party-body">
                                        <p>DFCS, Fulton County</p>
                                        <p>
                                            <label><i class="fa fa-phone" aria-hidden="true"></i> Phone:</label>
                                            <span>(404) 645-8888</span>
                                        </p>
                                        <p>
                                            <label><i class="fa fa-envelope-o" aria-hidden="true"></i> Email:</label>
                                            <span></span>
                                        </p>
                                        <p>
                                            <label><i class="fa fa-fax" aria-hidden="true"></i> Fax:</label>
                                            <span>(404) 645-8888</span>
                                        </p>
                                    </div>
                                </div>
                            </div>
                            <div class="col-xs-6">
                                <div class="party-block">
                                    <div class="heading">
                                        <span>Case Worker</span>
                                        <span>
                                            <i class="fa fa-pencil" aria-hidden="true"></i>
                                            <i class="fa fa-trash" aria-hidden="true"></i>
                                        </span>
                                    </div>
                                    <div class="party-body">
                                        <p>McMillian, Antonio</p>
                                        <p>
                                            <label><i class="fa fa-phone" aria-hidden="true"></i> Phone:</label>
                                            <span>(404) 645-8888</span>
                                        </p>
                                        <p>
                                            <label><i class="fa fa-envelope-o" aria-hidden="true"></i> Email:</label>
                                            <span>antonio.mcmillan@dhs.ga.gov</span>
                                        </p>
                                        <p>
                                            <label><i class="fa fa-fax" aria-hidden="true"></i> Fax:</label>
                                            <span>(404) 645-8888</span>
                                        </p>
                                    </div>
                                </div>
                            </div>
                            <div class="col-xs-6">
                                <div class="party-block">
                                    <div class="heading">
                                        <span>Hearing Coordinator</span>
                                        <span>
                                            <i class="fa fa-pencil" aria-hidden="true"></i>
                                            <i class="fa fa-trash" aria-hidden="true"></i>
                                        </span>
                                    </div>
                                    <div class="party-body">
                                        <p>Kirby, Shannon</p>
                                        <p>
                                            <label><i class="fa fa-phone" aria-hidden="true"></i> Phone:</label>
                                            <span>(706) 962-4721</span>
                                        </p>
                                        <p>
                                            <label><i class="fa fa-envelope-o" aria-hidden="true"></i> Email:</label>
                                            <span>shhill@dhr.state.ga.us</span>
                                        </p>
                                        <p>
                                            <label><i class="fa fa-fax" aria-hidden="true"></i> Fax:</label>
                                            <span></span>
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div> 
        </div>
       <!--  <div class="row" id="footer">
            <div class="container">
                <div class="col-xs-6">
                    <p class="footer-left">OSAH 2016 All Rights Reserved.</p>
                </div>
                <div class="col-xs-6">
                    <p class="footer-right">Designed and Developed by <a href="">Azul Arc</a></p>
                </div>
            </div>
        </div> -->
        
        <!-- Modal -->
        <div id="addparty" class="modal fade" role="dialog">
            <div class="modal-dialog">
                <!-- Modal content-->
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">
                            <img src="images/close.png" alt="close" />
                        </button>
                        <h4 class="modal-title">Add Party</h4>
                    </div>
                    <div class="modal-body">
                        <div class="row">
                            <div class="col-xs-4">
                                <label>Contact Type*</label>
                                <div class="dropdown">
                                    <select>
                                        <option>Select</option>
                                        <option>Select</option>
                                        <option>Select</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-xs-4">
                                <label>Last Name*</label>
                                <input type="text" />
                            </div>
                            <div class="col-xs-4">
                                <label>First Name*</label>
                                <input type="text" />
                            </div>
                            <div class="col-xs-4">
                                <label>Middle Name</label>
                                <input type="text" />
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-xs-4">
                                <label>Title</label>
                                <input type="text" />
                            </div>
                            <div class="col-xs-8">
                                <label>Company Name</label>
                                <input type="text" />
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-xs-12">
                                <label>Address Line 1</label>
                                <input type="text" />
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-xs-12">
                                <label>Address Line 2</label>
                                <input type="text" />
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-xs-4">
                                <label>City</label>
                                <input type="text" />
                            </div>
                            <div class="col-xs-4">
                                <label>State</label>
                                <div class="dropdown">
                                    <select>
                                        <option>Select</option>
                                        <option>Select</option>
                                        <option>Select</option>
                                    </select>
                                </div>
                            </div>
                            <div class="col-xs-4">
                                <label>Zip Code</label>
                                <input type="text" />
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-xs-4">
                                <label>Phone</label>
                                <input type="text" />
                            </div>
                            <div class="col-xs-4">
                                <label>Email</label>
                                <input type="text" />
                            </div>
                            <div class="col-xs-4">
                                <label>Fax</label>
                                <input type="text" />
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-xs-12">
                                <p>* Required Fields</p>
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <div class="btn-block">
                            <button type="button" class="btn btn-default cancel" data-dismiss="modal">CANCEL</button>
                            <button type="button" class="btn btn-default">SAVE</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        
        <div id="document-templates" class="modal fade" role="dialog">
            <div class="modal-dialog">
                <!-- Modal content-->
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">
                            <img src="images/close.png" alt="close" />
                        </button>
                        <h4 class="modal-title">Document Template</h4>
                    </div>
                    <div class="modal-body">
                        <div class="row">
                            <div class="col-xs-12">
                                <h4>What type of document?*</h4>
                                <div class="radio-block">
                                    <span>
                                        <input id="doctype1" name="doctype" type="radio" class="field radio" value="First Choice" tabindex="1" checked />
                                        <label class="" for="doctype1" >
                                            <span class="choice__text">Non-Decision Document</span>
                                        </label>
                                    </span>
                                    <span>
                                        <input id="doctype2" name="doctype" type="radio" class="field radio" value="First Choice" tabindex="1" />
                                        <label class="" for="doctype2" >
                                            <span class="choice__text">Decision Document</span>
                                        </label>
                                    </span>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-xs-4">
                                <label>Documents List*</label>
                                <div class="dropdown">
                                    <select>
                                        <option>Select</option>
                                        <option>Select</option>
                                        <option>Select</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-xs-12">
                                <label>Description</label>
                                <textarea></textarea>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-xs-12">
                                <h4>Mailer List <i>(Select users to be on the mailer list)</i></h4>
                                <div class="select-check">
                                    <span>
                                        <input id="mailerlist1" name="mailerlist" type="checkbox" class="field radio" value="First Choice" tabindex="1" />
                                        <label class="" for="mailerlist1" >
                                            <span class="choice__text">Petitioner</span>
                                        </label>
                                    </span>
                                    <span>
                                        <input id="mailerlist2" name="mailerlist" type="checkbox" class="field radio" value="First Choice" tabindex="1" />
                                        <label class="" for="mailerlist2" >
                                            <span class="choice__text">Respondent</span>
                                        </label>
                                    </span>
                                    <span>
                                        <input id="mailerlist3" name="mailerlist" type="checkbox" class="field radio" value="First Choice" tabindex="1" />
                                        <label class="" for="mailerlist3" >
                                            <span class="choice__text">Case Worker</span>
                                        </label>
                                    </span>
                                    <span>
                                        <input id="mailerlist4" name="mailerlist" type="checkbox" class="field radio" value="First Choice" tabindex="1" />
                                        <label class="" for="mailerlist4" >
                                            <span class="choice__text">Hearing Coordinator</span>
                                        </label>
                                    </span>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-xs-12">
                                <p>* Required Fields</p>
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <div class="btn-block">
                            <button type="button" class="btn btn-default cancel" data-dismiss="modal">CANCEL</button>
                            <button type="button" class="btn btn-default">ATTACH</button>
                            <button type="button" class="btn btn-default">OPEN</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        
        <div id="add-files" class="modal fade" role="dialog">
            <div class="modal-dialog">
                <!-- Modal content-->
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">
                            <img src="images/close.png" alt="close" />
                        </button>
                        <h4 class="modal-title">Attach Files</h4>
                    </div>
                    <div class="modal-body">
                        <div class="row">
                            <div class="col-xs-4">
                                <label>Document Type*</label>
                                <div class="dropdown">
                                    <select>
                                        <option>Select</option>
                                        <option>Select</option>
                                        <option>Select</option>
                                    </select>
                                </div>
                            </div>
                            <div class="col-xs-4">
                                <label>Date Filed*</label>
                                <div class="datepicker-wrapper">
                                    <input  type="text" id="datepicker4">
                                    <i class="fa fa-calendar" aria-hidden="true"></i>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-xs-12">
                                <label>Description</label>
                                <textarea></textarea>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-xs-12">
                                <label>Add Files</label>
                                <textarea class="add-files-area"></textarea>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-xs-12">
                                <p>* Required Fields</p>
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <div class="btn-block">
                            <button type="button" class="btn btn-default cancel" data-dismiss="modal">CANCEL</button>
                            <button type="button" class="btn btn-default">ATTACH</button>
                            <button type="button" class="btn btn-default">OPEN</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        
        <div id="add-decision" class="modal fade" role="dialog">
            <div class="modal-dialog">
                <!-- Modal content-->
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">
                            <img src="images/close.png" alt="close" />
                        </button>
                        <h4 class="modal-title">Disposition</h4>
                    </div>
                    <div class="modal-body">
                        <div class="row">
                            <div class="col-xs-6">
                                <label>Disposition Type</label>
                                <div class="dropdown">
                                    <select>
                                        <option>Select</option>
                                        <option>Select</option>
                                        <option>Select</option>
                                    </select>
                                </div>
                            </div>
                            <div class="col-xs-6">
                                <label>Disposition Date</label>
                                <div class="datepicker-wrapper">
                                    <input  type="text" id="datepicker5">
                                    <i class="fa fa-calendar" aria-hidden="true"></i>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-xs-6">
                                <label>Date Signed by Judge</label>
                                <div class="datepicker-wrapper">
                                    <input  type="text" id="datepicker6">
                                    <i class="fa fa-calendar" aria-hidden="true"></i>
                                </div>
                            </div>
                            <div class="col-xs-6">
                                <label>Date Mailed</label>
                                <div class="datepicker-wrapper">
                                    <input  type="text" id="datepicker7">
                                    <i class="fa fa-calendar" aria-hidden="true"></i>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-xs-6">
                                <h4>Was there a hearing?*</h4>
                                <div class="radio-block">
                                    <span>
                                        <input id="hearing1" name="hearing" type="radio" class="field radio" value="First Choice" tabindex="1" checked />
                                        <label class="" for="hearing1" >
                                            <span class="choice__text">Yes</span>
                                        </label>
                                    </span>
                                    <span>
                                        <input id="hearing2" name="hearing" type="radio" class="field radio" value="First Choice" tabindex="1" />
                                        <label class="" for="hearing2" >
                                            <span class="choice__text">No</span>
                                        </label>
                                    </span>
                                </div>
                            </div>
                            <div class="col-xs-6">
                                <p>* Required Fields</p>
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <div class="btn-block">
                            <button type="button" class="btn btn-default cancel" data-dismiss="modal">CANCEL</button>
                            <button type="button" class="btn btn-default">SAVE</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        
        <div id="confidential-case" class="modal fade" role="dialog">
            <div class="modal-dialog">
                <!-- Modal content-->
                <div class="modal-content">
                    <div class="modal-header">
                        <h4 class="modal-title"><i class="fa fa-exclamation-triangle" aria-hidden="true"></i> WARNING - CONFIDENTIAL CASE</h4>
                    </div>
                    <div class="modal-body">
                        <div class="row">
                            <div class="col-xs-12">
                                <h2>Please Note: This Case is CONFIDENTIAL.</h2>
                                <h2>Please follow the below rules for this case type.</h2>
                                <ul>
                                    <li>DO NOT share any information with a public caller.</li>
                                    <li>DO NOT...</li>
                                    <li>DO NOT...</li>
                                    <li>DO NOT...</li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <div class="btn-block">
                            <button type="button" class="btn btn-default cancel" data-dismiss="modal">CANCEL</button>
                            <button type="button" class="btn btn-default">OK</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!--Page Leaving Warning Modal Open here-->
		<div id="page-leave-warning-popup" class="deletepopup  modal fade" role="dialog" data-backdrop="static">
			<div class="modal-dialog">
				<!-- Modal content-->
				<div class="modal-content">
					<div class="modal-header">
						<button type="button" class="close" data-dismiss="modal">
							<img src="images/close.png" alt="close" />
						</button>
						<h4 class="modal-title">Warning</h4>
					</div>
					<div class="modal-body">
						<div class="row">
							<div class="col-xs-12">
								<p>Do you want to the save changes before leaving this page?</p>
							</div>
						</div>
					</div>
					<div class="modal-footer">
						<div class="btn-block">
							<button type="button" ng-click="pageLeaveWarning.proceedAhead()" class="btn btn-default cancel">CANCEL</button>
							<button type="button" ng-click="addDocket()" data-dismiss="modal" class="btn btn-default">Save</button>
						</div>
					</div>
				</div>
			</div>
		</div>
	<!--Page Leaving Warning Modal Ends here-->
        
    
