<html lang="en">

<!-- 
     DEVELOPER NAME:  AMOL SHRAWANE
     CREATED DATE:  SEPT 21 2016
     PURPOSE: THIS WORKS AS A LAYOUT FOR THE WHOLE APPLICATION.
     WORK FOR: OSAH, ATLANTA, GA
-->

    <head>
        <title>OSAH</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
	<meta name="viewport" content="width=1280">
        <link rel="shortcut icon" href="./img/favicon.ico" type="image/x-icon">
        <link rel="icon" href="./img/favicon.ico" type="image/x-icon">
        <!-- Bootstrap -->
        <link href="css/bootstrap.min.css" rel="stylesheet">
        <link href="css/datepicker.css" rel="stylesheet">
       <link href="https://fonts.googleapis.com/css?family=PT+Serif|Raleway:400,500,700|Roboto" rel="stylesheet">
        <link rel="stylesheet" href="css/font-awesome.min.css">
        <link rel="stylesheet" href="css/jquery-ui.css"> 
        <link rel="stylesheet" href="css/bootstrap-select.min.css">
		
        <link rel="stylesheet" href="js/select2-master/dist/css/select2.min.css"> 
        <link href="css/style.css" rel="stylesheet">
        <link href="css/dropzone.css" rel="stylesheet">
		 <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
        
        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
          <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
        <![endif]-->

    </head>
	

    <body ng-app="osah" ng-class="{loading: loading}" class="loading">
           <div ng-show="errorMessageshow" ng-controller="commancontroller" class="top-error-msg">
                <div class="alert alert-danger">
                    <a ng-click="removemodel()" style="cursor:pointer" class="close"  aria-label="close" title="close"><img src="images/close-white.png" alt="Close" /></a>
                    <span ng-bind="errorMessage" ></span>
                </div>
            </div>
            <div  class="row" id="wrap">
                <?php require_once "header.phtml"; ?>
                <div ui-view></div>
            </div>

   
        <?php require_once "end.php"; ?>
		<?php require_once 'loader.phtml'; ?>

        <?php require_once 'page-leave-warning-popup.phtml'; ?>
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
        <script src="js/jquery.js"></script>
        <!-- Include all compiled plugins (below), or include individual files as needed -->
		 <script src="js/angular/angularjs.js"></script>
         <script src="js/angular/jquery-ui.min.js"></script>
		 <script src="js/angular/angular-ui-router.min.js"></script>
         <script src="/js/angular/ocLazyLoad.min.js"></script>
		 
		 
      <script src="js/angular/app.js"></script>
 
     <script src="js/bootstrap-datepicker.js"></script>
     <script src="js/bootstrap.min.js"></script>
     <script src = "js/angular/factory/factory.js"></script>
     <script src = "js/angular/filter/filter.js"></script>
     <script src = "js/angular/directive/directive.js"></script>
	 <script src="js/angular/angular-filter.js"></script>
     <script src = "js/angular/controllers/commancontroller.js"></script>
     <script src = "js/dropzone.js"></script>
     <script src = "js/ng-dropzone.min.js"></script>
     <script src = "js/bootstrap-select.min.js"></script>
	 <script src="js/select2-master/dist/js/select2.full.js"></script>
		

		
      <script src="js/script.js"></script>
      <script type="text/javascript">
        </script>
 </body>
    
</html>