<div class="new-docket-title-block">
	<div class="container">
		<div class="new-docket-title-wrapper">
			<div class="col-xs-12">
				<h2>Calendar Management</h2>
			</div>
		</div>
	</div>
</div>
<div class="tab-block">
	<div class="container">
		<ul>
			<li>
				<a ui-sref="upcalendar"><i class="fa fa-calendar" aria-hidden="true"></i> Upcoming Calendars</a>
			</li>
			<li>
				<a class="active"><i class="fa fa-calendar-check-o" aria-hidden="true"></i> Calendar Management</a>
			</li>
			<li>
				<a ui-sref="calendarhistory()"><i class="fa fa-history" aria-hidden="true"></i> History</a>
			</li>
		</ul>
	</div>
</div>
<div class="search-for-calendar-management-block">
	<div class="container">
		<div class="panel-group" id="accordion">
			<div class="panel panel-default">
				<div class="panel-heading">
					<h4 class="panel-title">
						<a class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#accordion" data-target="#collapseOne">
							Search for Calendar
						</a>
					</h4>
				</div>
				<div id="collapseOne" class="panel-collapse collapse">
					<div class="panel-body">
						<div class="search-for-calendar-wrapper">
							<div class="col-xs-3">
								<label>Select Judge</label>
								<div class="dropdown">
									<select ng-model="calSearch.judge_id">
										<option value="">Select</option>
										<option ng-repeat="judges in cmjudgeslist | orderBy:'LastName'" value="{{judges.user_id}}">{{judges.LastName}}, {{judges.FirstName}}</option>
									</select>
								</div>
							</div>
							<div class="col-xs-3">
								<label>Select Assistant</label>
								<div class="dropdown">
									<select ng-model="calSearch.judge_assistant_id">
										<option value="">Select</option>
										<option ng-repeat="assistant in cmjudgeassistantlist | orderBy:'LastName'" value="{{assistant.user_id}}">{{assistant.LastName}}, {{assistant.FirstName}}</option>
									</select>
								</div>
							</div>
							<div class="col-xs-3">
								<a ng-click="listJudge()"><i class="fa fa-search" aria-hidden="true"></i> SEARCH</a>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<div class="search-default-view-block" ng-hide="calendarFlag">
	<div class="container">
		<p>Select a Judge or Assistant and then click <span>"Search"</span></p>
	</div>
</div>
<div class="new-calendar-block">
	<h2 ng-if="judgeList.length==0">
		<span class="create-new-calendar-btn-block" >
			<a data-toggle="modal" data-target="#create-new-calendar">Create New Calendar</a>
		</span>
	</h2>
	<div ng-repeat="(judge, calendar) in judgeList track by $index">
		<h2>{{judge}}</h2>
		<span class="create-new-calendar-btn-block" ng-if="$index==0">
			<a data-toggle="modal" data-target="#create-new-calendar">Create New Calendar</a>
		</span>
		<div class="calendar-tiles-block">
			<div class="calendar-item" ng-repeat="item in calendar">
				<div class="col-xs-4">
					<div class="calendar-tiles" ng-class="{active:(('pi'+$parent.$index+'i'+$index)==activeCalendarTiles)}">
						<div class="top">
							<span class="heading">{{item.casetypegroup}}</span>
							<span class="icon-block">
								<a ng-click="editCalendar(item)"><i class="fa fa-pencil" aria-hidden="true"></i></a>
								<a  ng-click="deleteConfirmation('calendar',item.Calendarid,'calendar_delete')"><i class="fa fa-trash-o" aria-hidden="true"></i></a>
							</span>
						</div>
						<div class="middle">
							<p><i class="fa fa-clock-o" aria-hidden="true"></i> {{item.hearingtime}}</p>
							<p><i class="fa fa-map-marker" aria-hidden="true"></i> {{item.location}}</p>
							<p>Max Number of Cases: {{item.noofcases}}</p>
						</div>
						<div class="bottom">
							<span class="calendat-dates-label-block">
								<a>Calendar dates</a>
							</span>
							<span class="icon-block">
								<a ng-click="toggleCalendarDatesViewFn(getParentChildRowNo($parent.$index,$index),item.Calendarid);toggleCalendarTiles($parent.$index,$index,item.Calendarid)"><i class="fa fa-eye" aria-hidden="true"></i> View</a>
								<a ng-click="toggleCalendarDatesBlockFn(getParentChildRowNo($parent.$index,$index),item.Calendarid);toggleCalendarTiles($parent.$index,$index,item.Calendarid)"><i class="fa fa-pencil" aria-hidden="true"></i> Add/Edit</a>
							</span>
						</div>
					</div>
				</div>
				
				<div class="calendar-dates-wrapper" ng-if="((($index+1)==getRowNo($index))||$last)&&(getParentChildRowNo($parent.$index,$index))==showCalendarDatesBlock">
					<div class="calendar-dates-block arrow" ng-class="{'arrow-left':pos.i%3==0,'arrow-center':pos.i%3==1,'arrow-right':pos.i%3==2}">
		<!--                            <a class="tip"><img src="images/point-arrow.jpg" /></a>-->
						<div class="top arrow-border">
							<span>Calendar Dates</span>
						</div>
						<div class="middle">
							<p>Enter the date and click <span>"Add Date"</span> button to continue adding dates.</p>
							<div class="col-xs-4" ng-repeat="item in calendarDatesList.data">
								<div>
									<div class="datepicker-wrapper">
										<input type="text" b-datepicker="{{item.hearingdate}}" datepicker-options="{autoclose: true}"  ng-model="item.hearingdate" ng-change="hearingDate()">
										<i class="fa fa-calendar" aria-hidden="true"></i>
									</div>
									<i class="fa fa-trash-o" aria-hidden="true" ng-click="deleteConfirmation('calendarDate',item)"></i>
								</div>
								<a class="add-date-btn" ng-if="$last" ng-click="addDateInput(calendarDatesList.calendarId)"><i class="fa fa-plus" aria-hidden="true"></i> Add Date</a>
							</div>
							<div class="col-xs-4" ng-if="calendarDatesList.data.length==0">
								<a class="add-date-btn" ng-click="addDateInput(calendarDatesList.calendarId)"><i class="fa fa-plus" aria-hidden="true"></i> Add Date</a>
							</div>
						</div>
						<div class="bottom">
							<button type="button" ng-click="toggleCalendarDatesBlockFn()" class="btn btn-default cancel" data-dismiss="modal">CANCEL</button>
							<button type="button" class="btn btn-default" ng-click="updateCalendarDates()">SAVE</button>
						</div>
					</div>
				</div>
			
				<div class="calendar-view-date-wrapper"  ng-if="((($index+1)==getRowNo($index))||$last)&&getParentChildRowNo($parent.$index,$index)==showCalendarDatesView">
					<div class="calendar-view-date-block arrow" ng-class="{'arrow-left':pos.i%3==0,'arrow-center':pos.i%3==1,'arrow-right':pos.i%3==2}">
						<div class="top arrow-border">
							<span class="icon-block"><a ng-click="toggleCalendarDatesBlockFn(getParentChildRowNo(pos.pi,pos.i),pos.calId);toggleCalendarTiles(pos.pi,pos.i,pos.calId)" ><i class="fa fa-pencil" aria-hidden="true"></i> Add/Edit Dates</a></span>
						</div>
						<div class="middle">
							<div class="row" ng-repeat="d in calendarDatesList.data | orderBy :year:reverse" ng-if="d.dates.length">
								<hr ng-if="!$first"/>
								<h1 class="date text-center">{{d.year}}</h1>
								<hr/>
								<div class="calendar-view-date-middle-block" ng-repeat="item in d.dates | orderBy :'hearingdate'">
									<div class="col-xs-4" ng-class="{center:(($index+1)%3)==2}">
										<span class="hearing-date-block">
											<h4 class="label">Hearing Date</h4>
											<h2 class="date">{{item.hearingdate | date:'MMM d'}}</h2>
										</span>
										<span class="cut-off-date-block">
											<h4 class="label">Cut Off Date</h4>
											<h2 class="date">{{item.cutoffdate | date:'MMM d'}}</h2>
										</span>
										<span class="delete">
											<a ng-click="deleteConfirmation('calendarDate',item)"><i class="fa fa-trash-o" aria-hidden="true"></i></a>
										</span>
									</div>
									<div class="clearfix" ng-if="(($index+1)%3)==0"></div>
									<hr ng-if="(($index+1)%3)==0&&!$last" />
								</div>
							</div>
						</div>
					</div>
				</div>	
				
				
				
				
				
				
				
				
				
				
			</div>
		</div>
	</div>
	
	
		
		
		
		
</div>
<div id="create-new-calendar" class="modal fade" data-backdrop="static" role="dialog">
	<div class="modal-dialog">
		<!-- Modal content-->
		<div class="modal-content">
			<div class="modal-header">
				<button ng-click="closeModal()" type="button" class="close" data-dismiss="modal">
					<img src="images/close.png" alt="close" />
				</button>
				<h4 class="modal-title">{{(calData.Calendarid)?'Edit':'Create New'}} Calendar</h4>
			</div>
			<div class="modal-body">
				<div class="row">
					<div class="col-xs-6">
						<label>Judge *</label>
						<div class="dropdown">
							<select name="Judge" ng-model="calData.judge_id" ng-change="validateCalendar(calData)" class="req" mesg="Please select a judge!" id="Judge">
							   <option value="">Select</option>
								<option ng-repeat="judges in cmjudgeslist | orderBy:'LastName'" value="{{judges.user_id}}">{{judges.LastName}}, {{judges.FirstName}}</option>
							</select>
						</div>
					</div>
					<div class="col-xs-6">
						<label>Assistant *</label>
						<div class="dropdown">
							<select name="Judgassistant" ng-model="calData.judge_assistant_id" ng-change="validateCalendar(calData)" class="req" mesg="Please select assistant judge!" id="Judgassistant">
								<option value="">Select</option>
								<option ng-repeat="assistant in cmjudgeassistantlist | orderBy:'LastName'" value="{{assistant.user_id}}">{{assistant.LastName}}, {{assistant.FirstName}}</option>
							</select>
						</div>
					</div>
				</div>
				<div class="row">
					<div class="col-xs-6">
						<label>Hearing Site *</label>
						<div class="dropdown">
							<select name="Hearingsite" ng-model="calData.court_location_id" ng-change="validateCalendar(calData)" class="req" mesg="Please select hearing site!" id="Hearingsite">
								<option value="">Select</option>
								<option ng-repeat="hearingsite in cmaloacationlist | orderBy :'Locationname'" value="{{hearingsite.courtlocationid}}">{{hearingsite.Locationname}}</option>
							</select>
						</div>
					</div>
					<div class="col-xs-6">
						<label>Hearing Time *</label>
						<div class="dropdown">
							<select name="Hearingtime" ng-model="calData.hearingtime_id" class="req" mesg="Please select hearing time!" id="Hearingtime"  ng-change="validateCalendar(calData)">
								<option value="">Select</option>
								<option ng-repeat="hearingtime in hearingtimelist | orderBy :'heringtimestored'" value="{{hearingtime.timeid}}">{{hearingtime.hearingtime}}</option>
							</select>
						</div>
					</div>
				</div>
				<div class="row">
					<div class="col-xs-6">
						<label>Case Type Group *</label>
						<div class="dropdown">
							<select name="Castypegroup" ng-model="calData.casetype_group_id" ng-change="validateCalendar(calData)" class="req" mesg="Please select case type group!" id="Castypegroup">
								<option value="">Select</option>
								<option ng-repeat="casetype in casetypegrouplist | orderBy :'casetypegroup'" value="{{casetype.id}}">{{casetype.casetypegroup}}</option>
							</select>
						</div>
					</div>
					<div class="col-xs-6">
						<label>Max Number of Cases</label>
						<input type="text" placeholder="(Enter #)" name="noofcases" ng-model="calData.noofcases" id="noofcases" />
					</div>
					
					<div class="col-xs-12">
						<?php /*To show loader when element data is loading @created by FaisalK 2016-02-27 start*/ ?>
						<div class="element-val-loader" ng-if="elementDataLoader.loadingVal||elementDataLoader.errorVal">
							<span class="calendar-form-element"  ng-if="elementDataLoader.loadingVal"><i class="fa fa-gavel"></i> {{elementDataLoader.text}}</span>
							<span class="calendar-form-element error"  ng-if="elementDataLoader.errorVal"><i class="fa fa-times"></i> Invalid Data - Combination of Judge, Assistant, Hearing Site, Hearing Time and Case Type Group already exists.</span>
						</div>
						<?php /*To show loader when element data is loading @created by FaisalK 2016-02-27 end*/ ?>
					</div>
				</div>
			</div>
			<div class="modal-footer">
				<div class="btn-block">
					<button type="button" class="btn btn-default cancel"  ng-click="closeModal()" data-dismiss="modal">CANCEL</button>
					<button type="button" class="btn btn-default" ng-click="checkselection()" toggle-class="clickevent" ng-disabled="isDisabled||elementDataLoader.loadingVal||elementDataLoader.errorVal" >SAVE</button>
				</div>
			</div>
		</div>
	</div>
</div>
<div id="delete-confirmation" class="deletepopup  modal fade" data-backdrop="static" role="dialog">
	<div class="modal-dialog">
		<!-- Modal content-->
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal">
					<img src="images/close.png" alt="close" />
				</button>
				<h4 class="modal-title">Delete</h4>
			</div>
			<div class="modal-body">
				<div class="row">
					<div class="col-xs-12">
						<p>Do you want to delete the calendar{{(deleteData.type=='calendarDate')?' date':''}}?</p>
					</div>
				</div>
			</div>
			<div class="modal-footer">
				<div class="btn-block">
					<button type="button" class="btn btn-default cancel" data-dismiss="modal">CANCEL</button>
					<button type="button" ng-click="(deleteData.type=='calendarDate')?deleteDateInput(deleteData.id,deleteData.date):deleteCalendar(deleteData.id)"  class="btn btn-default">OK</button>
				</div>
			</div>
		</div>
	</div>
</div>

<!--Page Leaving Warning Modal Open here-->
	<div id="page-leave-warning-popup" class="deletepopup  modal fade" role="dialog" data-backdrop="static">
		<div class="modal-dialog">
			<!-- Modal content-->
			<div class="modal-content">
				<div class="modal-header">
					<button type="button"   data-dismiss="modal" class="close" data-dismiss="modal">
						<img src="images/close.png" alt="close" />
					</button>
					<h4 class="modal-title">Warning</h4>
				</div>
				<div class="modal-body">
					<div class="row">
						<div class="col-xs-12">
							<p>Do you want to the save changes before leaving this page?</p>
						</div>
					</div>
				</div>
				<div class="modal-footer">
					<div class="btn-block">
						<button type="button" ng-click="pageLeaveWarning.proceedAhead()" class="btn btn-default cancel">CANCEL</button>
						<button type="button" ng-click="updateCalendarDates()" data-dismiss="modal" class="btn btn-default">Save</button>
					</div>
				</div>
			</div>
		</div>
	</div>
<!--Page Leaving Warning Modal Ends here-->   