
            <div class="dds-title-block">
                <div class="container">
                    <div class="dds-title-wrapper">
                        <div class="col-xs-12">
                            <h2>DDS Import & Reports</h2>
                        </div>
                    </div>
                </div>
            </div>
            <div class="tab-block">
                <div class="container">
                    <ul>
                        <li>
                            <a ui-sref="ddsreport"><i class="fa fa-book" aria-hidden="true"></i> Reports</a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="dds-import-block">
                <div class="container">
                    <div class="dds-import-wrapper">
                        <h3>Select button to import from DDS</h3>
                        <a class="import-btn"><i class="fa fa-download" aria-hidden="true"></i> Import</a>
                    </div>
                </div>
            </div>
            
            
            
    
     