
        <div >
            <!-- <div class="header-wrapper">
                <div class="header">
                    <div class="container">
                        <div class="col-xs-3">
                            <a href="index.html" class="logo"><img src="images/osah-logo.png" alt="OSAH" /></a>
                        </div>
                        <div class="col-xs-7">
                            <div class="navigation">
                                <ul>
                                    <li><a href="index.html">HOME</a></li>
                                    <li><a href="calendar-management.html">CALENDAR</a></li>
                                    <li><a class="active" href="docket.html">DOCKET</a></li>
                                </ul>
                            </div>
                        </div>
                        <div class="col-xs-2">
                            <a href="login.html" class="logout"><i class="fa fa-sign-out" aria-hidden="true"></i> LOGOUT</a>
                        </div>
                    </div>
                </div>
                <div class="inner-page">
                    <div class="container">
                        <div class="col-xs-3">
                            <div class="back-to-search-result-wrapper">
                                <a><i class="fa fa-angle-left" aria-hidden="true"></i> Back to Search Results</a>
                            </div>
                        </div>
                        <div class="col-xs-6">
                            <div class="docket-number-block">
                                <label>Docket Number</label>
                                <input type="text" />
                                <span class="search"><i class="fa fa-search" aria-hidden="true"></i></span>
                            </div>
                            <div class="additional-search-btn">
                                <span>+</span> Additional Search Options
                            </div>
                        </div>
                        <div class="col-xs-3 visible-hidden"></div>
                    </div>
                </div>
            </div> -->

            <div class="overview-block">
                <div class="container">
                    <div class="overview-wrapper">
                        <div class="col-xs-4">
                            <span>Docket Number</span>
                            <h2>{{docket_no}}</h2>
                        </div>
                      <div class="col-xs-3">
							<span>Petitioner</span>
							<h2 ng-show="petitioner_flg==1">{{Lastname | capitalize}}, {{Firstname | capitalize}}</h2>
							<h2 ng-show="petitioner_flg==0">{{petitionerName}}</h2>
						</div>
						<div class="col-xs-3">
							<span>Respondent</span>
							<h2 ng-show="respondent_flg==1">{{ReslastName | capitalize}}, {{ResfirstName | capitalize}}</h2>
							<h2 ng-show="respondent_flg==0">{{respondentName}}</h2>
						</div>
                        <div class="col-xs-2">
							<span class="createdby-label">Created By: {{docketCreated | capitalize}}</span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="tab-block" ng-class="{confidential:(casefiletype=='Confidential')}">
                <div class="container">
					<div class="confidential-warning pull-right" ng-if="(casefiletype=='Confidential')">
							<i class="fa fa-exclamation-triangle"></i> CONFIDENTIAL CASE
					</div>
                    <ul>
                        <li>
                            <a ng-href="#/docket/reqdt/{{reqdt}}"><i class="fa fa-info-circle" aria-hidden="true"></i> General Information</a>
                        </li>
                        <li>
                            <a class="active"><i class="fa fa-history" aria-hidden="true"></i> History</a>
                        </li>
                        <li>
                            <a ng-href="#/docnotes/reqdt/{{reqdt}}"><i class="fa fa-pencil-square-o" aria-hidden="true"></i> Notes</a>
                        </li>

                    </ul>
                </div>
            </div>
            <div class="history-table-block">
                <div class="container">
                    <div class="history-table-wrapper">
                        <table>
                            <tr class="header">
                                <td class="date" ng-click="sort_by('date')">Date <i class="fa fa-angle-up" aria-hidden="true"></i></td>
                                <td class="description"  ng-click="sort_by('Description')">Description <i class="fa fa-angle-down" aria-hidden="true"></i></td>
                                <td class="modified-by"  ng-click="sort_by('Modifiedby')">Modified By <i class="fa fa-angle-down" aria-hidden="true"></i></td>
                            </tr>
                            <tr ng-repeat="history in historyList | orderBy:sortingOrder:reverse | limitTo:historyList.limit">
                                <td class="date">{{history.date | date:'MM-dd-yyyy'}}</td>
                                <td class="description">
                                    <div class="label-block" compile="history.Description">
									
						            </div>
                                </td>
                                <td class="modified-by">{{history.Modifiedby}}</td>
                            </tr>
                         </table>
                    </div>
                </div>
            </div>
			<div class="load-more-button-block">
				<div class="container">
					<div class="button-block">
						<button class="more btn btn-primary btn-block" ng-click="loadMore()">Load More!</button>
						<button class="loadless btn btn-primary btn-block" ng-click="loadless()">Load Less!</button>
					</div>
				</div>
			</div>
        <div id="hidden-download-form" style="display:none;">
		</div>
        
