<!-- Search Result page -->
            <div class="search-results-block" ng-controller="commancontroller">
                <div class="container">
                    <div class="col-xs-12">
                        <div class="display-records-label">
                            <h2 ng-cloak>Displaying <span ng-if="result.total">{{searchCondition.start+1}}-{{lastRecordNo()}} records of</span> {{result.total}} <span ng-if="!result.total">record</span></h2>
                        </div>
                    </div>
                    <div class="col-xs-12">
                        <div class="page-number-btn-block">
                            <div class="col-xs-6">
                                <div class="dropdown">
                                    <label>Entries per page</label>

                                    <select ng-change="entriesPerPageChanged('{{searchCondition.length}}')"  ng-change="entriesPerPageChanged()"  ng-model="searchCondition.length" ng-options="a for a in entriesPerPageFn()" ></select>

                                </div>
                            </div>
                            <div class="col-xs-6">
                                <div class="btn-block">
                                    <a ng-show="showPrintflag=='1'" ng-click = "printResult()"><i class="fa fa-print" aria-hidden="true"></i> PRINT</a>
                                    <a ng-click="showPrintflag=='1' ? CalendarexportData() : exportData()"><i class="fa fa-share-square-o" aria-hidden="true"></i> EXPORT</a><br>
                                </div>
                            </div>
                        </div>
                    </div>
					<div>
					<div id="exportDataId">
					</div>
					<div id="printDataId">
					</div>
					<div id="calendarexportDataId">
					</div>
                    <div class="col-xs-12">
                        <div class="search-results-table">
                            <table>
                                <tr class="heading">
                                    <td ng-click="sortByClick('caseid')" class="docket">Docket <i class="fa fa-angle-down" aria-hidden="true"></i></td>
                                    <td ng-click="sortByClick('Lastname')" class="case-name">Case Name <i class="fa fa-angle-down" aria-hidden="true"></i></td>
                                    <td ng-click="sortByClick('casetype')" class="case-type">Case Type <i class="fa fa-angle-down" aria-hidden="true"></i></td>
                                    <td ng-click="sortByClick('datereceivedbyOSAH')" class="date-received">Date Received <i class="fa fa-angle-down" aria-hidden="true"></i></td>
                                    <td ng-click="sortByClick('hearingdate')" class="hearing-date">Hearing Date <i class="fa fa-angle-down" aria-hidden="true"></i></td>
                                    <td ng-click="sortByClick('hearingtime')" class="hearing-time">Hearing Time <i class="fa fa-angle-down" aria-hidden="true"></i></td>
                                    <td ng-click="sortByClick('hearingsite')" class="hearing-location">Hearing Location <i class="fa fa-angle-down" aria-hidden="true"></i></td>
                                    <td ng-click="sortByClick('status')" class="status">Status <i class="fa fa-angle-down" aria-hidden="true"></i></td>
                                    <td ng-click="sortByClick('judge')" class="judge">Judge <i class="fa fa-angle-down" aria-hidden="true"></i></td>
                                </tr>
								<?php /* @Edited by FaisalK 03-11-2016 @purpose format of case name and judge as per u341*/?>
                                <tr ng-repeat="data in result.data" ng-click="searchbydocket(data.caseid)">
                                    <td class="docket" ng-click="searchbydocket(data.caseid)">{{data.caseid}}</td>
                                    <td class="case-name">{{data.Lastname |capitalize}}{{(data.Firstname&&data.Lastname)?', ':'No party Added'}}{{data.Firstname |capitalize}}</td>
                                    <td class="case-type">{{data.casetype}}</td>
                                    <td class="date-received">{{data.datereceiveddisplay}}</td>
                                    <td class="hearing-date">{{data.hearingdateDisplay}}</td>
                                    <td class="hearing-time">{{data.hearingtimeDisplay}}</td>
                                    <td class="hearing-location">{{data.hearingsite}}</td>
                                    <td class="status">{{data.status}}</td>
                                    <td class="judge">{{data.judge.replace(" ", ", ") |capitalize}}</td>
                                </tr>
                            </table>
							<div class="no-record" ng-show="empty_result_flag=='1'">
									No Results found.
							</div>
                        </div>
                    </div>
                    <div class="col-xs-12">
                        <div class="table-pagination">
                            <nav aria-label="Page navigation">
                                <ul class="pagination">
                                    <li ng-hide="(searchCondition.start/searchCondition.length)<1">
                                        <a href="" ng-click="paginationClick(0)"  aria-label="First">
                                            <i class="fa fa-angle-double-left" aria-hidden="true"></i> First
                                        </a>
                                    </li>
                                    <li ng-hide="(searchCondition.start/searchCondition.length)<1">
                                        <a href="" aria-label="Previous" ng-click="paginationClick((searchCondition.start/searchCondition.length)-1)">
                                            <i class="fa fa-angle-left" aria-hidden="true"></i> Prev
                                        </a>
                                    </li>
                                    <li ng-repeat="a in paginationFn()"><a href=""  ng-class="{'active':a==(searchCondition.start/searchCondition.length)}" ng-click="paginationClick(a)">{{a+1}}</a></li>
                                    <li ng-hide="lastRecordNo()==result.total">
                                        <a href="" aria-label="Next" ng-click="paginationClick((searchCondition.start/searchCondition.length)+1)">
                                            Next <i class="fa fa-angle-right" aria-hidden="true"></i>
                                        </a>
                                    </li>
                                    <li ng-hide="lastRecordNo()==result.total">
                                        <a href=""  ng-click="paginationClick(lastPagination())"  aria-label="Last">
                                            Last <i class="fa fa-angle-double-right" aria-hidden="true"></i>
                                        </a>
                                    </li>
                                </ul>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>
            