 <div data-dojo-type="dijit/layout/TabContainer" data-dojo-props="region:'center'">
        <!--   FOURTH DIV STATEMENT STARTS HERE  -->   
            <div data-dojo-type="dijit/layout/ContentPane" title="Login" style="overflow: auto">
           <!--  <div data-dojo-type="dijit/form/Form" id="myForm1" data-dojo-id="myForm1" encType="multipart/form-data" align="left" action="" method=""> --> 


               <form method="post" action="login.php">
    User: <input type="text" name="userLogin" /><br />
    Password: <input type="password" name="userPassword" /><br />
    <input type="submit" name="submit" value="Submit" />
</form>                 
               
                Gireesh, foo page<strong>Module:</strong>        Osahform &raquo;
<strong>Controller:</strong>    Osahform &raquo;
<strong>Action:</strong>        foo
               <table class="pageTable" ><tr><td colspan="4"><center><h1><br>
                 <br>
                 <br>
                <br>
                <br>
                 <br>
                 <p><font size="+2">Welcome to OSAH CASE Management System</font></p></h1></center></td></tr>
                 
               </table>
                  
		     </div>  <!--   FOURTH DIV STATEMENT ENDS HERE  -->
                
         </div> <!--   THIRD DIV STATEMENT ENDS HERE  -->
         </div>